export const USER_SIGNIN_API = 'USER_SIGNIN_API';
export const USLOGIN = 'USLOGIN';


export const GET_ALL_PROJECT_CATEGORY_SAGA = 'GET_ALL_PROJECT_CATEGORY_SAGA';
export const GET_ALL_PROJECT_CATEGORY = 'GET_ALL_PROJECT_CATEGORY';

export const GET_ALL_PRIORITY = 'GET_ALL_PRIORITY';
export const GET_ALL_PRIORITY_SAGA = 'GET_ALL_PRIORITY_SAGA';

export const GET_ALL_PROJECT = 'GET_ALL_PROJECT';
export const GET_ALL_PROJECT_SAGA = 'GET_ALL_PROJECT_SAGA';

export const GET_ALL_STATUS_SAGA = 'GET_ALL_STATUS_SAGA';
export const GET_ALL_STATUS = 'GET_ALL_STATUS';

export const GET_TASK_DETAIL_SAGA = 'GET_TASK_DETAIL_SAGA';
export const GET_TASK_DETAIL = 'GET_TASK_DETAIL';


export const CHANGE_TASK_MODAL = 'CHANGE_TASK_MODAL';
export const CHANGE_ASSIGNESS = 'CHANGE_ASSIGNESS';
export const REMOVE_USER_ASSIGN = 'REMOVE_USER_ASSIGN'

export const UPDATE_STATUS_TASK_SAGA = 'UPDATE_STATUS_TASK_SAGA';


export const UPDATE_TASK_SAGA = 'UPDATE_TASK_SAGA';
export const HANDLE_CHANGE_POST_API_SAGA = 'HANDLE_CHANGE_POST_API_SAGA';

export const GET_ALL_TASK_TYPE = 'GET_ALL_TASK_TYPE';
export const GET_ALL_TASK_TYPE_SAGA = 'GET_ALL_TASK_TYPE_SAGA';

export const GET_USER_BY_PROJECT_ID_SAGA = 'GET_USER_BY_PROJECT_ID_SAGA';
export const GET_USER_BY_PROJECT_ID = 'GET_USER_BY_PROJECT_ID';

export const DISPLAY_LOADING = 'DISPLAY_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';